### PR TITLE
Unify file handling for local and remote transports (#189)

### LINKED ISSUE #189: Local transport on Windows creates LinuxFile instead of WindowsFile
InSpec's file resource behaves strangely when running locally on Windows because LinuxFile is used instead of WindowsFile. This causes various methods to fail with error like so:
```
>inspec shell -c "file(\"C:\\log\").type"
C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `instance_eval': undefined method `name' for nil:NilClass (NoMethodError)
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.26.1/lib/train/transports/local_file.rb:75:in `stat'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.26.1/lib/train/extras/file_unix.rb:49:in `block (2 levels) in <class:UnixFile>'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/resources/file.rb:52:in `call'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/resources/file.rb:52:in `block (2 levels) in <class:FileResource>'
        from (eval):1:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `instance_eval'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:144:in `load_with_context'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/profile_context.rb:130:in `load_control_file'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/runner.rb:215:in `eval_with_virtual_profile'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/cli.rb:254:in `run_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/lib/inspec/cli.rb:204:in `shell_func'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.33.13/bin/inspec:12:in `<top (required)>'
        from C:/opscode/inspec/bin/inspec:62:in `load'
        from C:/opscode/inspec/bin/inspec:62:in `<main>'
```

See [Train::Transports::Local::Connection.file](https://github.com/chef/train/blob/e10d65bc1fc828f27291956a5f574e0e5c44b7fc/lib/train/transports/local.rb#L43)
`@files[path] ||= File.new(self, path)`

Should there be conditional logic to create WindowsFile when running locally on Windows?

### PR DESCRIPTION
**Pull request by tpcwang**
Local and remote transports expose different file interfaces. This
is because local transport uses LinuxFile with some methods
overriden with Ruby's File calls whereas remote transport uses
the appropriate file classes from Train::Extras. This causes
problems when users are running locally on Windows because some
LinuxFile implementations are not appropriate there.

There are two potential compat breaks with this change:
1. pw_username is no longer provided for local transport
2. pw_groupname is no longer provided for local transport

These are not available for remote transport, so this doesn't
seem like it should be a problem for clients.

Fixes #189

### CODE REVIEW

**Comment by chris-rock** [comment]
Thank you @tpcwang for providing this PR. It highlights an issue that we have with train on Windows.`pw_username` and `pw_groupname` are private functions and are not exposed.

I think this PR is going in a great direction. Nevertheless, I believe we should not give up the local implementations too early. It improves the speed if InSpec since we can use the Ruby file implementation instead of using commands to emulate the behavior. 

Instead, I propose that we have a `local_linux_file.rb`  and a `local_windows_file.rb` that overrides the methods that can be optimized.

**Comment by tpcwang** [comment]
Okay. I didn't realize local_file was added for performance reasons. I'll look at this again in the near future. @Vasu1105 if you get to this before I do in #193, I would recommend that you pull in the tests that I have created so that we have better coverage on Windows.

**Comment by Vasu1105** [comment]
ok @tpcwang

**Comment by clintoncwolfe** [comment]
As this has been stale for a long time, and train has grown a great deal in that time, I'm going to go ahead and close this.  Please d re-open if you feel that is best and you have time to contribute.

**Pull request closed without merging**
