### PR TITLE
Ensure unique_identifier returns something meaningful for service acc…

### PR DESCRIPTION
**Pull request by skpaterson**
…ounts.

Signed-off-by: Stuart Paterson <spaterson@chef.io>

### CODE REVIEW

**Comment by tomqwu** [comment]
@jquick, do you have any idea when this will be released to gem? and I assume a PR downstream to InSpec?

**Comment by jquick** [comment]
Released a new train gem today, and releasing inspec with it now!

**Comment by tomqwu** [comment]
@jquick indeed this fixes the issue as I was doing some test locally by building inspec from source with latest gem, here is the PR https://github.com/inspec/inspec/pull/3331 for bumping the version if it's not yet

**Comment by jquick** [comment]
Gotcha, yeah it should update if you do another bundle install but we can pin up for the next release

**Pull request merged**
