### PR TITLE
[SUSTAIN-955] Add data callbacks to WinRM and SSH

### PR DESCRIPTION
**Pull request by marcparadise**
In order to support existing bootstrap functionality for `knife
bootstrap`s conversion to Train, clients need a method to receive
data from the target host as it is being generated.

This callback will be invoked for SSH when data arrives on the channel,
and for WinRM when data is returned on stdout.

Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>

### CODE REVIEW

**Comment by marcparadise** [comment]
@jerryaldrichi I have added some tests.  Though in the he case of SSH, I wonder if there's value in it - E_TOO_MUCH_MOCKING.

**Comment by marcparadise** [comment]
@clintoncwolfe I've updated this to use blocks from your suggestion in the review meeting. That's expanded the scope of the change a bit, but it is a bit cleaner - and has the advantage of not invoking the callback for internal train commands used for platform detection.   Callback handling has been added to winrm and ssh; if we need it for other transports, we can have separate implementation PRs for those.

**Comment by marcparadise** [comment]
The failing test is a transient failure that I saw locally, it seems to depend on the test case randomization sequence.

**Comment by clintoncwolfe** [comment]
@marcparadise could you take care of the merge conflict? After that I think we're ready to merge.

**Comment by clintoncwolfe** [comment]
Adopted on #431 to fix merge conflict

**Pull request closed without merging**
