### PR TITLE
Fix fallback regex for OpenSuse

### PR DESCRIPTION
**Pull request by n-rodriguez**
See https://github.com/inspec/train/issues/377

This regex matches both case :

`VERSION = 15.0` and 
`VERSION="15.0"`

Thank you!

### CODE REVIEW

**Comment by tas50** [comment]
@n-rodriguez Can you add a comment above the regex with a permalink from rubular. https://rubular.com/

That way we can have a link in the code to show the various things we're trying to match instead of having to track things back to this PR.

Also you'll need to sign this commit off for the DCO before we can merge it. https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by n-rodriguez** [comment]
@tas50 done! Thank you!

**Comment by robbkidd** [comment]
Seems OK with more variants: https://rubular.com/r/b5PN3hZDxa5amV

And an example for the regex appearing above it: https://rubular.com/r/UKaYWolCYFMfp1

**Comment by n-rodriguez** [comment]
@robbkidd done! thank you! :+1:

**Comment by zenspider** [comment]
I dunno... should I be the anal-retentive regexp-er? I am not sure it actually matters because this is coming from some vendored source?

I'm gonna approve, but just so you know, that `\s` accepts things like tabs or newlines. You probably just want `<space>?`... and the `"?` allows for the quotes to be on one side and not the other. Again, probably doesn't matter, but in other contexts that sort of thing is crucial.

**Comment by n-rodriguez** [comment]
I'm gonna change \s to space

**Comment by zenspider** [comment]
I meant `/ ?/` (added slashes so you can see the space, vs `/\s?/`. The first one only accepts a space.

**Comment by n-rodriguez** [comment]
> I meant `/ ?/` (added slashes so you can see the space, vs `/\s?/`. The first one only accepts a space.

Ok. Do you want me to change it?

**Comment by zenspider** [comment]
I'll get it. Just consider it for next time.

**Comment by n-rodriguez** [comment]
> I'll get it. Just consider it for next time.

I'll remember! Thanks!

**Pull request merged**
