### PR TITLE
Fix for wrong OS detection in Windows Subsystem for Linux

### PR DESCRIPTION
**Pull request by christian-wtd**
This fixes the wrong OS detection in Windows Subsystem for Linux (WSL)

## Description
We earlier detected windows because running cmd.exe works in WSL but we can detect that by running "which cmd.exe" which gives commadn not found in windows because which is a linux command.

## Related Issue
https://github.com/inspec/train/issues/520
https://github.com/inspec/inspec/issues/4310 (potentially)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by christian-wtd** [comment]
Is your build test kidding me? 
5 Failures and 2 Errors and nothing of that is in the code I submitted?
Maybe I oversee a correlation here...

**Comment by christian-wtd** [comment]
Alright, my initial approach was fixing WSL but breaking evrything else :-( 
Fixed that!

**Comment by christian-wtd** [comment]
Oh btw...
Your Rubocop makes opposite offenses than mine (0.74.0).
Even Code Climate agrees and suggests to use single quotes, which my rubocop does too and yours offenses...

**Comment by christian-wtd** [comment]
In addition to the original bug this may fix also
https://github.com/inspec/train/pull/515

**Comment by zenspider** [comment]
Sorry, but WSL is not a supported platform and isn't on our radar.

**Comment by bohdanyurov-gl** [comment]
@zenspider Fix takes two lines, why can't we add it? What is the possible negative impact?

**Comment by Schwad** [comment]
@bohdanyurov-gl We don't actively track closed PRs/issues so comments like this are easily lost in the ether. 

I know it's been most of a year since this PR was filed, if you'd like to continue the discussion feel free to file an issue :) 

I personally have no problem with WSL but someone from @inspec/foundation-team-reviewers may have more background on this than me. Thanks!

**Pull request closed without merging**
