### PR TITLE
Fixed ssh connection issue if key_files array is empty

### PR DESCRIPTION
**Pull request by sanga1794**
Signed-off-by: sanga17 <sausekar@msystechnologies.com>

## Description
If key_files set as empty array then failing to ssh connection while bootstrapping the node

## Related Issue
https://github.com/chef/chef/issues/7053

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New content (non-breaking change)
- [ ] Breaking change (a content change which would break existing functionality or processes)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by tas50** [comment]
Is there a bug to link here and can we get a test added for this?

**Comment by sanga1794** [comment]
> Is there a bug to link here and can we get a test added for this?

@tas I'm working on the issue https://github.com/chef/chef/issues/7053, while trying to bootstrap a node using the ssh config_file, as `key_files` from `chef` repo is `[]`(if we didn't mentioned in CLI), then not able to connect with the node using ssh.

**Comment by sanga1794** [comment]
@tas50, @marcparadise Please review this PR Thanks!!

**Comment by marcparadise** [comment]
How does having an empty array for key_files cause a failure?

**Comment by sanga1794** [comment]
> How does having an empty array for key_files cause a failure?

@marcparadise below i attached the screenshot which consist of both failing and working `Net::SSH.start` method, please have look. Thanks!!
And we are deleting from list of options if value of any variable is nil for reference: https://github.com/inspec/train/blob/7121af0ea78734e4bf8081f14fb72a5f85378477/lib/train/transports/ssh_connection.rb#L213
Screenshot from 2021-07-28 15-52-28

**Comment by sanga1794** [comment]
> > How does having an empty array for key_files cause a failure?
> 
> @marcparadise below i attached the screenshot which consist of both failing and working `Net::SSH.start` method, please have look. Thanks!!
> And we are deleting from list of options if value of any variable is nil for reference:
> 
> https://github.com/inspec/train/blob/7121af0ea78734e4bf8081f14fb72a5f85378477/lib/train/transports/ssh_connection.rb#L213
> 
> 
> Screenshot from 2021-07-28 15-52-28

@marcparadise, @tas50 Please have look into this. Thanks!!!

**Comment by marcparadise** [comment]
If auth method were `public-key,keyboard-interactive` I'd then expect to receive a password prompt (if tty enabled). With just `public-key` if the key is not present, it can't succeed.   Based on that understanding, it seems like what you're seeing is correct. 

Is there something different that you'd expect, or am I misunderstanding something in that output?

**Pull request closed without merging**
